services:
  orders_back_db:
    image: postgres:17.4
    container_name: orders_back_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_PS_DATABASE}
      POSTGRES_USER: ${DB_PS_USERNAME}
      POSTGRES_PASSWORD: ${DB_PS_PASSWORD}
    command: >
      postgres
        -c max_connections=${MAX_CONNECTIONS}
        -c shared_buffers=${SHARED_BUFFERS}
        -c work_mem=${WORK_MEM}
        -c maintenance_work_mem=${MAINTENANCE_WORK_MEM}
        -c wal_buffers=${WAL_BUFFERS}
        -c checkpoint_timeout=${CHECKPOINT_TIMEOUT}
        -c effective_cache_size=${EFFECTIVE_CACHE_SIZE}
        -c random_page_cost=${RANDOM_PAGE_COST}
        -c logging_collector=${LOGGING_COLLECTOR}
        -c log_statement=${LOG_STATEMENT}
        -c log_min_duration_statement=${LOG_MIN_DURATION_STATEMENT}
    ports:
      - ${DB_PS_PORT}:${DB_PS_DOCKER_PORT}
    volumes:
      - ${DB_PS_DOCKER_VOLUME}:/var/lib/postgresql/data:rw,noatime
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 2G
          cpus: '2.0'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_PS_USERNAME} -d ${DB_PS_DATABASE}']
      interval: 10s       # Chequea cada 10 segundos
      timeout: 5s         # Si no responde en 5 seg, cuenta como fallo
      retries: 3          # Si falla 3 veces seguidas, es Unhealthy
      start_period: 30s   # Tiempo de gracia para asignar la memoria (shared_buffers, etc.)

  # --- NUEVO SERVICIO ADMINER ---
  adminer:
    image: adminer
    container_name: orders_adminer # Un nombre descriptivo para este proyecto
    restart: always
    ports:
      - 8082:8080
    depends_on:
      orders_back_db:
        condition: service_healthy
    environment:
      # Esto pre-selecciona "PostgreSQL" en el panel de login
      ADMINER_DEFAULT_SERVER: orders_back_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_backend_api
    restart: unless-stopped
    depends_on:
      orders_back_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_PS_USERNAME}:${DB_PS_PASSWORD}@orders_back_db:5432/${DB_PS_DATABASE}?schema=public
    ports:
      - "3000:3000"
    volumes:
      # Volumen anónimo para proteger los node_modules del contenedor
      # y evitar que se sobreescriban si montas carpetas locales en el futuro
      - /app/node_modules

# Si tu variable ${DB_PS_DOCKER_VOLUME} hace referencia a un volumen nombrado de Docker 
# (y no a una ruta local como ./data), asegúrate de declararlo aquí abajo.
# Si es una ruta local, puedes borrar este bloque 'volumes:'.
volumes:
  pg_data: # Sustituye 'pg_data' por el valor real de ${DB_PS_DOCKER_VOLUME} si aplica.